const variable = {
  ref: document.querySelector(".ref"),
  country: [
    "CANADA", "EEUU", "MEXICO", "BERMUDAS", "GROELANDIA", 
    "BAHAMAS", "BARBADOS", "BELICE", "COSTA RICA", "CUBA",
    "DOMINICA", "REP DOMINICA", "EL SALVADOR", "GRANADA", 
    "GUATEMALA", "haiti", "honduras", "jamaica", "nicaragua", 
    "panama", "puerto rico", "Argentina", "Aruba", "bolivia", 
    "BRASIL", "CHILE", "COLOMBIA", "ECUADOR", "GUYANA",
    "PARAGUAY", "PERU", "SURINAM", "URUGUAY", "VENEZUELA",
    "AFGANISTAN", "ARABIA SAUDITA", "ARMENIA", "AZERBAIJAN", 
    "BAHREIN", "BANGLA DESH", "BRUNEI", "BUTAN", "CAMBOYA", 
    "CHINA", "CHIPRE", "COREA", "FILIPINAS", "GEORGIA",
    "INDIA", "INDONESIA", "IRAK", "IRAN", "INDONESIA", 
    "IRAK", "IRAN", "ISRAEL", "JAPON", "JORDANIA", 
    "KASAKISTAN", "KIRGUISISTAN", "KUWAIT", "LAOS", "LIBANO", 
    "MALAYSIA", "MALDIVAS", "MONGOLIA", "NEPAL", "OMAN", 
    "PAKISTAN", "QATAR", "RUSIA", "SINGAPUR", "SIRIA",
    "SRI LANKA", "TADJIKISTAN", "TAIWAN", "THAILANDIA", "TURKEMENISTAN", 
    "TURQUIA", "UZBEKISTAN", "VIETNAM", "YEMEN", "ALBANIA",
    "ALEMANIA", "ANDORRA", "AUSTRIA", "BELGICA", "BIELORRUSIA",
    "BOZNIA HERZEGOVINA", "BULGARIA", "REP CHECA", "CROACIA", 
    "DINAMARCA", "ESLOVAQUIA", "ESLOVENIA", "ESPAÑA", "ESTONIA", 
    "FINLANDIA", "FRANCIA", "GRAN BRETAÑA", "GRECIA", "HUNGRIA",
    "IRLANDA", "ISLANDIA", "ITALIA", "LETONIA", "LIECHTENSTEIN", 
    "LITUANIA", "LUXEMBURGO", "MACEDONIA", "MALTA", "MOLDAVIA", 
    "MONACO", "NORUEGA", "HOLANDA", "POLONIA", "PORTUGAL",
    "RUMANIA", "RUSIA", "SAN MARINO", "SUECIA", "SUIZA", 
    "UCRANIA", "YUGOSLAVIA", "ANGOLA", "ARGELIA", "BOTSWANA",
    "BURKINA FASO", "BURUNDI", "CABO VERDE", "CAMERUN",
    "CHAD", "CONGO", "COSTA DE MARFIL", "DJBUTI", "EGIPTO", 
    "ERITREA", "ETIOPIA", "GABON", "GAMBIA", "GHANA",
    "GUINEA", "GUINEA BISSAU", "GUINEA ECUATORIAL", "KENIA", "LESOTHO", 
    "LIBERIA", "LIBIA", "MADAGASCAR", "MALAWI", "MALI",
    "MARRUECOS", "MAURICIO", "MAURITANIA", "MOZAMBIQUE", "NAMIBIA",
    "NIGERIA", "RUANDA", "NIGER", "SENEGAL", "SEYCHELLES",
    "SIERRA LEONA", "SOMALIA", "REP SUDAFRICANA", "SUDAN",
    "SWAZILANDIA", "TANZANIA", "TOGO", "TUNICIA", "UGANDA", 
    "ZAMBIA", "ZIMBABWE", "AUSTRALIA", "FIJI", "KIRIBATI",
    "MARSHALL", "MICRONESIA", "NAURU", "NUEVA ZELANDA",
    "SALOMON", "TONGA", "TUVALU", "VANUATU", "HAWAI"
  ],
  random: Math.floor(Math.random() * 184)
}

console.log(variable);

export default variable;